### ISSUE TITLE
conan don't find freetype!

### ISSUE THREAD

**Issue by zzjfengqing** [dimi309/small3d#60]

**Comment by dimi309** [comment]
You may be missing the new default conan repositories. They changed after they moved to bintray. What does conan show if you run `conan remote list`?

**Comment by zzjfengqing** [comment]
I have configured conan repositories,but only freetype is not find.I am very depressed，may you package this  these lib to my email: 450282550@qq.com?  I am very interested in this project and very much hope to run this project.

**Comment by dimi309** [comment]
It is not safe to be receiving libraries by e-mail. I'm sorry.

You can clone freetype from its source repository on github:

`git clone https://github.com/lasote/conan-freetype`

Then you just need to export it to your local conan repository:

```
cd freetype
conan export lasote/stable
```

Then, try to build small3d again. It should work now if that was the only problem. Still, I find it very strange that freetype could not be found by conan. Could you please execute `conan remote list` and show me the output?

**Comment by zzjfengqing** [comment]
I am glad to receive your reply. I will try again at a later time.
